server:
  port: 9200

spring:
  application:
    name: payment-service

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
        enabled: false
        username: nacos
        password: nacos


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

seata:
  enabled: false
  tx-service-group: default_tx_group
  registry:
    type: file
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      default_tx_group: default


alipay:
  app-id: 9021000165623463
  private-key: |
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCZmh9MCEhcdLEp23IPULf3K2qUVF+MpnsYpY3HbNbm0F6HgsgWZST3T2JvBR9RyzJS+5/0rUEig4RbJOz8mbcA2lq0sVaNrGGKdwVM40+P+g5bXohFu7rUn81k6MhfP31i/vOrwnCXz5gwQPIcAYy6fyWDeIJ2VXBkoAYBQMHHtgCRUDbcIS154z0mT+TfCBozpNpsB/W5GQ7UhqwWnzVhhoTMBBO6S1aqRYkFwm8DjNhZV0ZUaP7xoQmgcj8aj+6rRIG9Fm8oif3dRgBhe3imj9CTI/ZYQ4FAen1N/9ljfqTMlCtyRi9W/vgyAf91umzV7CmntiQp4Tv4MBNRhpltAgMBAAECggEANyTFp54xnD+oesZ1pFnuMaY8lRPVWcFK4AZPaBEC9cpIpY2mF6QoKUEurXzBSbQRVQlQ2553i9R7Z91R1z24HW5GsigYUrRYMEWaeYgBwEadcN/3PFGxOTRFoLyRcuBwO2IcSMV9doLouCoYwUUtKKcM6K4S6Di0KOvqO/jrmK6FhIymQM0qnZROcED0K01zRq/Z2GtdJFECAfprHDD+XlXjx1+FGemLjGTKiqMkkx0oeY4/j6c/83AveDtZ/k55ju+qM8VPy4MMjfANQGKmPPGsZDkEwhN/FxRq00n2NWF+szb5lY0M78ruupSIRZ4lUDdIpSQwGQJTUY8HNJqNAQKBgQDvo1X9sqTx7T9WnYwsutbwR2fZaN5YxkqsEKHiVP+keq/GtT85q1JB4Gd/NIissxPVVhl46CKgBjBy1ESIcuEFSk4Zg2RcnnSEac9LQTeS1Wsr4HsL8eZE5WkCL8apFkiSaWe8Wu7EXNsaPCxyefSprgZJFkYFIGeXLzw43347RQKBgQCkFvPAXvsbfKK5qAU3Wu0F11A8Mz3r0J4YDERlO/bYMvUC4ms7y3DLx7AAxVNb4Y7oelVK4MEb3Zke2D9FvUPvPSxzJ9tLBdTMkYf+rKuVZEAilpKIydqnvdOSMDCODnRwWFF2hx9VbJsilDiTv+cRmfbXd564cPIRM3hqNGK0CQKBgQCQk1eG5ueSudLzu7tdJSAV+M6ToSw8HO3iH2q7dRKCti4kUSci8NSAwBVQ7m3i22uE0xwtEMgLCZDjRmNOexh9K5Yw2E+NfV/In1mcCm2v3ah54UX7L+b/+/Q9iHtvee0wv/0A60+QEoFxs4oRSrisQjyyjYiTATjeQnYvzc6HjQKBgBdXuIc2O8yWN2Pn1g4g3jUFg0F9HKLuQ38yR4yLMjthTF+DrDOOZlZm6s/BQnGArd6+gGGthWscZAryQlX+baqb7jXXhqeuha4wScNd9u7CmykQeHoDFRrlszJJrq6WudO9jKEq6bcyQwNxSHckRo/HckkGmEqurpDp3IhnOV9ZAoGBAIeN7MMdDHqwsWCYPWwd21Anz33hmr9rFEMSpIk2dy4ZSc6oAmioHG1rsFx+qieIBw5yD8SMxUxqqfc4xs7ZCo4WzhgsNDjxL2mSW56ZGHm8GWQLQ3O+VLXIoBnsRX1oO6FulDxGlVlHnNu3f/m8DQNluhqCL5Pt3RPE3h2rNsGG
  alipay-public-key: |
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4nzd840+V2FjxR+ahzrNSzLp63SvrHs8uVBto7rJCZsilMB1ODrn3AwWJOcq1AGO5riTSYXs1hF4c8w4I0f8Yt5prl+dC2o3hH4/tyoBTaNb4XpHKaR2frvFQwyg7seitSGfnVDyfFEgnY7Ps9eJp/8E+pXaXRHzEYqV3vpYIVNvtFCaTkU+IYZwcDo+opDzyT6FFV7ktH1ma061z4xqMn8ioH0Z0fyt980JB5T/jd0YHbsMU60fxJbljXt/kFa8hFaHUZIUMfVRFHd2DqFbWZTli2WFJVfEn0bOpAyxQAU/HjDChvB7yWARjU8EhjM4CyUn7QHPKqLrXvBVj2krqwIDAQAB
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  return-url: http://localhost:5173/#/pay/result
  notify-url: https://stomach-invitations-turtle-created.trycloudflare.com/api/payments/notify
