server:
  port: 8093
spring:
  application:
    name: log-service

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  datasource:
    url: jdbc:mysql://localhost:3306/log_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        password: nacos
        username: nacos

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0